version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/src'
    ports:
      - 5001:5000

#  frontend-prod:
#    container_name: frontend-prod
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile.prod
#    ports:
#      - '1337:80'
